# Generated by Django 2.0.7 on 2018-07-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='random_number',
            field=models.IntegerField(default=43),
        ),
    ]
