# Generated by Django 2.0.7 on 2018-07-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20180727_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='random_number',
            field=models.IntegerField(default=99),
        ),
    ]
